version: "3.7"

services:
  app_proxy:
    environment:
      # <app-id>_<web-container-name>_1
      # e.g. 'btc-rpc-explorer_web_1'
      # Note that the '_1' at the end is needed
      APP_HOST: sovreign-librewolf_app_1
      APP_PORT: 3000
  
  web:
    image: ghcr.io/linuxserver/librewolf:135.0.1@sha256:da15e8950d4e36de6c9ecd2930f6a6a89a960bb669e5aa08495b8da624f0b48d
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/config
    shm_size: "1gb"
    restart: on-failure
